AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Generic Deploy Policies from https://github.com/someimportantcompany/aws-iam-generic-deploy-role-policy
Resources:

  GenericPolicy1:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-policy1
      Description:
        Fn::Sub: ${AWS::StackName} (Policy 1) Generic read permissions
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ec2:Describe*"
            Resource: "*"

  GenericPolicy2:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-policy2
      Description:
        Fn::Sub: ${AWS::StackName} (Policy 2) Lambda
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow all Lambda actions
          - Effect: Allow
            Action: lambda:*
            Resource:
              Fn::Sub: 'arn:aws:lambda:*:${AWS::AccountId}:function:${!aws:PrincipalTag/DeployNamePrefix}*'
            Condition:
              "Null":
                aws:PrincipalTag/DeployNamePrefix: "false"
          # Except Invoke*
          - Effect: Deny
            Action: lambda:Invoke*
            Resource: '*'
