AWSTemplateFormatVersion: '2010-09-09'
Description: Generic Test Roles to test Generic Deploy Policies from https://github.com/someimportantcompany/aws-iam-generic-deploy-role-policy

Parameters:
  DeployPolicyPrefix:
    Type: String
  DeployNamePrefix:
    Type: String
  DeployTagKey:
    Type: String
  DeployTagValue:
    Type: String

Resources:

  TestDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-test-deploy-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${DeployPolicyPrefix}-policy1
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${DeployPolicyPrefix}-policy2
      Tags:
        - Key: DeployNamePrefix
          Value:
            Ref: DeployNamePrefix
        - Key: DeployTagKey
          Value:
            Ref: DeployTagKey
        - Key: DeployTagValue
          Value:
            Ref: DeployTagValue

  TestExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-test-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ecs-tasks.amazonaws.com
                - ecs.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
