AWSTemplateFormatVersion: '2010-09-09'
Description: Generic Test Roles to test Generic Deploy Policies from https://github.com/someimportantcompany/aws-iam-generic-deploy-role-policy

Parameters:
  RoleName:
    Type: String
  PolicyPrefix:
    Type: String
  DeployNamePrefix:
    Type: String
  DeployTagKey:
    Type: String
  DeployTagValue:
    Type: String

Resources:

  TestDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${PolicyPrefix}-policy1
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${PolicyPrefix}-policy2
      Tags:
        - Key: DeployNamePrefix
          Value:
            Ref: DeployNamePrefix
        - Key: DeployTagKey
          Value:
            Ref: DeployTagKey
        - Key: DeployTagValue
          Value:
            Ref: DeployTagValue
