AWSTemplateFormatVersion: '2010-09-09'
Description: Generic Test Roles to test Generic Deploy Policies from https://github.com/someimportantcompany/aws-iam-generic-deploy-role-policy

# This is an example of a template you can use to bootstrap your own Deployment roles
# But you should use your own IaC tool to create lots of roles for each of your applications/services
# Instead of using this for production - this creates one role at a time

Parameters:
  RoleName:
    Type: String
  PolicyPrefix:
    Type: String
  DeployNamePrefix:
    Type: String
  DeployTagKey:
    Type: String
  DeployTagValue:
    Type: String

Resources:

  TestDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: { Fn::Sub: "arn:aws:iam::${AWS::AccountId}:root" }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${PolicyPrefix}1
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${PolicyPrefix}2
      Tags:
        - Key: DeployNamePrefix
          Value:
            Ref: DeployNamePrefix
        - Key: DeployTagKey
          Value:
            Ref: DeployTagKey
        - Key: DeployTagValue
          Value:
            Ref: DeployTagValue
